// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZI0QWIvWqwB1grw2DIN7Bp7CfnGrrfHc',
    appId: '1:733231722253:android:edc090dd25c098ae71ca44',
    messagingSenderId: '733231722253',
    projectId: 'mat-security',
    databaseURL: 'https://mat-security-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mat-security.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm8srvk0UhCtFK6Zxi4H_GoMn5SP2Fbec',
    appId: '1:733231722253:ios:ccebddfcb9d36daf71ca44',
    messagingSenderId: '733231722253',
    projectId: 'mat-security',
    databaseURL: 'https://mat-security-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mat-security.appspot.com',
    iosClientId: '733231722253-c80tnotlj0fu6t56n46cau4paiv6njmm.apps.googleusercontent.com',
    iosBundleId: 'com.example.matSecurity',
  );
}
